const mongoose = require('mongoose');

const ThemeSettingSchema = new mongoose.Schema(
  {
    // Backward compatibility: old single theme id
    activeTheme: {
      type: String,
      enum: ['default', 'dark', 'softBlue'],
      default: 'default',
    },
    // New granular settings per area
    sidebarTheme: {
      type: String,
      enum: [
        'white',
        'black',
        'blue',
        'yellow',
        'gray',
        'green',
        'purple',
        'orange',
        'grayD1D5DB',
        'gray9CA3AF',
        'gray6B7280',
        'gray4B5563',
        'gray374151',
        'gray1F2937',
        'gray111827',
        'grayE5E7EB',
        'grayF3F4F6',
        'grayF9FAFB',
        'red7F1D1D',
        'red991B1B',
        'redB91C1C',
        'redDC2626',
        'redEF4444',
        'redF87171',
        'redFCA5A5',
        'purple4C1D95',
        'purple5B21B6',
        'purple6D28D9',
        'purple7C3AED',
        'purple8B5CF6',
        'purpleA78BFA',
        'purpleC4B5FD',
        'blue1E3A8A',
        'blue1D4ED8',
        'blue2563EB',
        'blue3B82F6',
        'blue60A5FA',
        'blue93C5FD',
        'blueBFDBFE',
        'cyan164E63',
        'cyan0E7490',
        'cyan0891B2',
        'cyan06B6D4',
        'cyan22D3EE',
        'cyan67E8F9',
        'cyanCFFAFE',
        'green14532D',
        'green166534',
        'green15803D',
        'green16A34A',
        'green22C55E',
        'green4ADE80',
        'green86EFAC',
        'yellow713F12',
        'yellow854D0E',
        'yellowA16207',
        'yellowCA8A04',
        'yellowEAB308',
        'yellowFACC15',
        'yellowFDE047',
        'orange7C2D12',
        'orange9A3412',
        'orangeC2410C',
        'orangeEA580C',
        'orangeF97316',
        'orangeFB923C',
        'orangeFDBA74',
        'brown451A03',
        'brown78350F',
        'brown92400E',
        'brownB45309',
        'brownD97706',
        'brownF59E0B',
        'brownFBBF24',
        // legacy ids (tetap diterima untuk kompatibilitas)
        'softWhite',
        'gray100',
        'gray200',
        'gray300',
        'blueBlack',
        'gray800',
        'navyDark',
        'blueDark',
        'skyBlue',
        'skySoft',
        'greenSoft',
        'limeSoft',
        'cream',
        'orangeSoft',
        'peach',
        'pinkSoft',
        'rose',
        'indigo',
        'cyanSoft',
      ],
      default: 'white',
    },
    sidebarTextColor: {
      type: String,
      enum: ['black', 'white'],
      default: 'white',
    },
    headerTheme: {
      type: String,
      enum: [
        'white',
        'black',
        'blue',
        'yellow',
        'gray',
        'green',
        'purple',
        'orange',
        'grayD1D5DB',
        'gray9CA3AF',
        'gray6B7280',
        'gray4B5563',
        'gray374151',
        'gray1F2937',
        'gray111827',
        'grayE5E7EB',
        'grayF3F4F6',
        'grayF9FAFB',
        'red7F1D1D',
        'red991B1B',
        'redB91C1C',
        'redDC2626',
        'redEF4444',
        'redF87171',
        'redFCA5A5',
        'purple4C1D95',
        'purple5B21B6',
        'purple6D28D9',
        'purple7C3AED',
        'purple8B5CF6',
        'purpleA78BFA',
        'purpleC4B5FD',
        'blue1E3A8A',
        'blue1D4ED8',
        'blue2563EB',
        'blue3B82F6',
        'blue60A5FA',
        'blue93C5FD',
        'blueBFDBFE',
        'cyan164E63',
        'cyan0E7490',
        'cyan0891B2',
        'cyan06B6D4',
        'cyan22D3EE',
        'cyan67E8F9',
        'cyanCFFAFE',
        'green14532D',
        'green166534',
        'green15803D',
        'green16A34A',
        'green22C55E',
        'green4ADE80',
        'green86EFAC',
        'yellow713F12',
        'yellow854D0E',
        'yellowA16207',
        'yellowCA8A04',
        'yellowEAB308',
        'yellowFACC15',
        'yellowFDE047',
        'orange7C2D12',
        'orange9A3412',
        'orangeC2410C',
        'orangeEA580C',
        'orangeF97316',
        'orangeFB923C',
        'orangeFDBA74',
        'brown451A03',
        'brown78350F',
        'brown92400E',
        'brownB45309',
        'brownD97706',
        'brownF59E0B',
        'brownFBBF24',
        // legacy ids (tetap diterima untuk kompatibilitas)
        'softWhite',
        'gray100',
        'gray200',
        'gray300',
        'blueBlack',
        'gray800',
        'navyDark',
        'blueDark',
        'skyBlue',
        'skySoft',
        'greenSoft',
        'limeSoft',
        'cream',
        'orangeSoft',
        'peach',
        'pinkSoft',
        'rose',
        'indigo',
        'cyanSoft',
      ],
      default: 'white',
    },
    headerTextColor: {
      type: String,
      enum: ['black', 'white'],
      default: 'black',
    },
    mainTheme: {
      type: String,
      enum: ['white', 'black', 'blue', 'yellow', 'gray', 'green'],
      default: 'gray',
    },
    // Global UI toggle: hide main hero banner on landing page
    hideMainHero: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('ThemeSetting', ThemeSettingSchema);

